= Група А
:toc: left
:source-highlighter: rouge


== Общи указания

В шаблона за изпита ще намерите дефинициите на няколко функции. Някои от тях са помощни. Те са напълно реализирани и можете да ги използвате наготово. Други са оставени празни. тях трябва да реализирате така, че да отговарят на спецификацията по-долу.

За всички функциите са написани unit test-ове, с които можете да проверите дали решението ви работи коректно. Възможно е тестовете да не покриват всички възможни случаи.

Ако искате да разберете по-добре как трябва да работят функциите, които трябва да реализирате, препоръчваме да разгледате unit test-овете.

В решението НЕ може:

* да променяте кода на помощните функции.
* да променяте прототипите на функциите, които трябва да се напишат (например не може да променяте имената им, типа на параметрите им, типа на връщаната стойност и т.н.)
* да променяте предоставените тестове.
* да добавяте нови файлове (решението ви трябва да разпишетев предоставените файлове).

Ако искате можете да дефинирате собствени помощни функции и/или тестове.


== Условие

В тази задача ще работим с аритметични изрази.
Те ще се представят като символни низове. 

В аритметичния израз може да участват операциите събиране (`+`), изваждане (`-`), умножение (`*`), деление (`/`), степенуване (`^`).
Приоритетите им са стандартните, познати ви от курсовете по математика.
Операциите трябва да бъдат ляво асоциативни.

За улеснение считаме, че (1) всички числа в израза имат само по една цифра и също, че (2) в него НЯМА празни символи (whitespace).

За определеност считаме, че празният низ (`""`) също е валиден израз и има стойност `0` (нула).
`nullptr` НЕ Е валиден израз.
Например следните изрази са валидни (в коментар до тях са указани оценките им):

    ""        // оценка 0
    5+5       // оценка 10
    8/4/2     // оценка 1
    8-4-2     // оценка 2
    2^3*2+2-5 // оценка 13

Тези НЕ са валидни:

    55
    5+
    +5
    5+5+
    5  +  5

Довършете кода на следните функции:

verify::
Проверява дали даден израз е валиден.

evaluate::
Получава израз, пресмята го и връща неговата стойност.
Ако на функцията бъде подаден невалиден израз, да се хвърли изключение от тип `std::invalid_argument`.

В решението на задачата можете да използвате наготово `std::stack` от STL. За улеснение съответните header файлове са включени в `solution.cpp`.

В решението са включени и помощни функции, които можете да използвате наговото. Можете да ги намерите в `solution.h` и `solution.cpp`:

* `isDigit` -- Проверява дали даден символ е цифра.
* `isOperation` -- Проверява дали даден символ е операция
* `toDouble` -- Преобразува цифра (подадена като символ от тип `char`) до нейната числова стойност.
* `priority` -- Връща приоритетите на различните операции.
* `perform` -- Получава операция (представена като символ) и нейните аргументи. Прилага операцията върху аргументите и връща получения резултат. Например `perform('+', 1.1, 2.2)` ще върне `3.3`.

*Упътване*: За `verify` забележете, че коректните изрази са проста поредица от вида число, операция, число, ..., като винаги се започва и завършва с число.

За `evaluate` използвайте два стека. Един за операциите (`O`) и един за аргументите им (`A`). Започнете като вкарате първото число от израза в `A`. След това започнете да четете двойки операция и число. За всяка нова операция проверявайте в стека дали преди това не е имало друга с по-нисък или равен приоритет. Ако е така, изтеглете я от `O` заедно с аргументите ѝ от `A`, изпълнете я и накрая върнете резултата в A. Повторете това колкото пъти е нужно преди да продължите към нова двойка операция и аргумент. Ако всичко премине коректно, накрая ще имате само един елемент в стека `A` -- оценката на израза.
